[tool.poetry]
name = "modme-clone"
version = "0.1.0"
description = ""
authors = ["Ahror <uzkod136@mail.ru>"]
readme = "README.md"
packages = [{ include = "core" }]

[tool.poetry.dependencies]
python = "^3.10"
django = "^4.1.5"
psycopg2-binary = "^2.9.5"
django-environ = "^0.9.0"
drf-yasg = { extras = ["validation"], version = "^1.21.4" }
sentry-sdk = "^1.14.0"
django-parler = "^2.3"
djangorestframework = "^3.14.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
